#!/bin/bash

if [[ $(whoami) != "root" ]]
then
    echo "Il faut être root"
    exit 1
fi

packages="
neovim
alacritty
evince
nautilus
gnome-calculator
ranger
xournalpp
fzf
eog
glances
waylock
ripgrep
rofi
waybar
wl-mirror
wl-clipboard
dunst
gnome-disk-utility
mpd
mpc
fastfetch
pass
keychain
texlive
grim
zsh
zenity
discord
sddm
wtype
starship
ufw
libreoffice-still
git

pacman-contrib
snap-pac
ruby
python-pip
python-certifi
texlive-langfrench
python-pygments
libffi
python-cffi
python-pynvim
libnotify
libinput
libreoffice-still
acpi
mplayer
go
swaybg

wayland
xorg-xwayland
irqbalance
cpupower
pipewire
pipewire-alsa
pipewire-audio
pipewire-pulse
x86_energy_perf_policy
rxvt-unicode
terminus-font
whois
ethtool
foomatic-db
foomatic-db-ppds
foomatic-db-gutenprint-ppds
foomatic-db-nonfree
foomatic-db-nonfree-ppds
gutenprint
system-config-printer
transmission-gtk
bluez
bluez-utils
bluez-plugins
ttf-hack-nerd
xdg-utils
intel-media-driver
intel-gmmlib
cups
cups-filters
cups-pdf
avahi
bash
bash-completion

adwaita-cursors
adwaita-icon-theme
binutils
blueman
cryptsetup
dconf
default-cursors
desktop-file-utils
gnu-free-fonts
gnupg
gnutls
gtk-layer-shell
gtk-update-icon-cache
qt5-wayland
hunspell
libadwaita
pavucontrol
tar
vulkan-headers
vulkan-icd-loader
vulkan-intel
xdg-dbus-proxy
xdg-desktop-portal
xdg-user-dirs
noto-fonts-emoji
fwupd
rebuild-detector
unrar
"

#pipewire-jack

#adobe-source-code-pro-fonts
#ttf-liberation
#otf-font-awesome
#gsfonts
#gstreamer
#gst-plugins-bad
#gst-plugins-base
#gst-plugins-ugly
#gst-plugin-pipewire
#gstreamer-vaapi
#gst-plugins-good
#gst-libav
#gstreamer-vaapi
#a52dec
#faac
#faad2
#flac
#jasper
#lame
#libdca
#libdv
#libmad
#libmpeg2
#libtheora
#libvorbis
#libxv
#wavpack
#x264
#xvidcore

for package in $packages
do
    if [[ packages != "" ]]
    then
        pacman -S --needed --noconfirm $package &> /dev/null

        if [[ "$?" == "0" ]]
        then
            echo -e "\033[32mOK\033[0m $package"
        else
            echo -e "\033[31mERREUR\033[0m $package"
        fi
    fi
done

