#!/bin/bash

echo -en "\033[34m\t----- Post installation -----\033[0m\n\n"

if [[ $(whoami) != "root" ]]
then
    echo "Il faut être root"
    exit 1
fi

echo -e "\033[34m--- Activation de scrub ---\033[0m"
# C'est la checksum du système btrfs
systemctl enable --now btrfs-scrub@-.timer

echo -e "\033[34m--- Installation de snapper ---\033[0m"
sudo pacman --noconfirm -S snapper snap-pac

echo -e "\033[34m--- Configuration de snapper ---\033[0m"
umount /.snapshots/
rm -rf /.snapshots/
snapper -c root create-config /
systemctl enable --now snapper-timeline.timer
systemctl enable --now snapper-cleanup.timer

cat << EOF > /etc/snapper/configs/root
SUBVOLUME="/"
FSTYPE="btrfs"
QGROUP=""
SPACE_LIMIT="0.5"
FREE_LIMIT="0.2"
ALLOW_USERS=""
ALLOW_GROUPS=""
SYNC_ACL="no"
BACKGROUND_COMPARISON="yes"
NUMBER_CLEANUP="yes"
NUMBER_MIN_AGE="1800"
NUMBER_LIMIT="30"
NUMBER_LIMIT_IMPORTANT="10"
TIMELINE_CREATE="no"
TIMELINE_CLEANUP="yes"
TIMELINE_MIN_AGE="1800"
TIMELINE_LIMIT_HOURLY="0"
TIMELINE_LIMIT_DAILY="0"
TIMELINE_LIMIT_WEEKLY="0"
TIMELINE_LIMIT_MONTHLY="0"
TIMELINE_LIMIT_YEARLY="0"
EMPTY_PRE_POST_CLEANUP="yes"
EMPTY_PRE_POST_MIN_AGE="1800"
EOF

cat << EOF > /etc/snapper/configs/home
SUBVOLUME="/home"
FSTYPE="btrfs"
QGROUP=""
SPACE_LIMIT="0.5"
FREE_LIMIT="0.2"
ALLOW_USERS=""
ALLOW_GROUPS=""
SYNC_ACL="no"
BACKGROUND_COMPARISON="yes"
NUMBER_CLEANUP="yes"
NUMBER_MIN_AGE="1800"
NUMBER_LIMIT="30"
NUMBER_LIMIT_IMPORTANT="10"
TIMELINE_CREATE="yes"
TIMELINE_CLEANUP="yes"
TIMELINE_MIN_AGE="1800"
TIMELINE_LIMIT_HOURLY="5"
TIMELINE_LIMIT_DAILY="5"
TIMELINE_LIMIT_WEEKLY="5"
TIMELINE_LIMIT_MONTHLY="0"
TIMELINE_LIMIT_YEARLY="0"
EMPTY_PRE_POST_CLEANUP="yes"
EMPTY_PRE_POST_MIN_AGE="1800"
EOF

echo -e "\033[34m--- Configuration et activation du pare-feu ---\033[0m"
ufw default deny
ufw default allow outgoing
ufw allow https
ufw allow ssh
ufw allow 631/tcp # Pour autoriser l'imprimante
ufw limit ssh
ufw enable
systemctl enable ufw.service

echo -e "\033[34m--- Montage du disque backup ---\033[0m"
mount /dev/sdb1 /mnt

su - adrien << EOF
echo -e "\033[34m--- Installation du backup ---\033[0m"
cd /mnt
PATH="/home/adrien/.config/myscripts/:$PATH"
backup
cd ~

echo -e "\033[34m--- Remise à niveau des permissions ---\033[0m"
reset_perm
sudo chmod -x .ssh/*
sudo chmod 600 ~/.gnupg/*
sudo chmod 700 ~/.gnupg/

echo -e "\033[34m--- Installation de la zram ---\033[0m"
cd ~/.config/myscripts
sudo ./install_zram_state
cd ~

echo -e "\033[34m--- Configuration de l'agent gpg ---\033[0m"
echo "default-cache-ttl 3600" > ~/.gnupg/gpg-agent.conf

echo -e "\033[34m--- Importation des clés gpg ---\033[0m"
gpg --import .key_public.gpg
#gpg --edit-key 9D2FA1339D3E9F67150E689D68B835DCDA861664 trust quit
gpg --edit-key fadri1@proton.me sign quit

echo -e "\033[34m--- Initiation de pass storage ---\033[0m"
pass init 9D2FA1339D3E9F67150E689D68B835DCDA861664

echo -e "\033[34m--- Installation des plugins de neovim ---\033[0m"
nvim .config/nvim/lua/adrien-config/packer.lua

EOF

echo -e "\033[34m--- Démontage du disque backup ---\033[0m"
umount /mnt

echo -e "\033[34m--- Fin de la post-installation ---\033[0m"
