#!/bin/bash

if [[ $(whoami) != "root" ]]
then
    echo "Il faut être root"
    exit 1
fi

packages="
reflector
rsync
"

for package in $packages
do
    pacman -Rs --noconfirm $package &> /dev/null

    if [[ "$?" == "0" ]]
    then
        echo -e "\033[32mOK\033[0m $package"
    else
        echo -e "\033[31mERREUR\033[0m $package"
    fi
done
