#!/bin/bash

if [[ $(whoami) = "root" ]]
then
    echo "Il ne faut pas être root"
    exit 1
fi

echo -en "\033[34m\t----- Post installation -----\033[0m\n\n"

echo -en "\033[34m\t----- Partie administrateur -----\033[0m\n\n"

sudo ./post_install_root

echo -en "\033[34m\t----- Partie utilisateur -----\033[0m\n\n"

echo -e "\033[34m--- Installation de ma configuration ---\033[0m"
config="fish nvim starship.toml"
for folder in config
do
    rm -fr ~/.config/${folder}
    cp -r config/${folder} ~/.config
done

echo -e "\033[34m--- Installation de yay ---\033[0m"
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si --noconfirm
cd ..
rm -fr yay

echo -e "\033[34m--- Installation des paquets du AUR ---\033[0m"
yay --noconfirm -S arch-update
yay --noconfirm -S ufw-docker

echo -e "\033[34m--- Configuration de ufw pour docker ---\033[0m"
sudo ufw-docker install
sudo systemctl restart ufw

echo -e "\033[34m--- Configuration de crontab pour duckdns ---\033[0m"
(crontab -l; echo "*/5 * * * * /home/lebotdufutur/serveur/duckdns/duck.sh >/dev/null 2>&1") | crontab -

echo -e "\033[34m--- Fin de la post-installation ---\033[0m"

echo "Il faut lancer la commande 'yay --noconfirm -S docker-rootless-extras' et faire ce qu'il dit"
