#! /bin/bash

echo -e "\033[34m--- Activation de scrub ---\033[0m"
# C'est la checksum du système btrfs
systemctl enable --now btrfs-scrub@-.timer

echo -e "\033[34m--- Configuration et activation du pare-feu ---\033[0m"
ufw default deny
ufw default allow outgoing
ufw allow https
ufw allow ssh
ufw limit ssh
ufw enable
systemctl enable --now ufw.service

echo -e "\033[34m--- Installation de snapper ---\033[0m"
pacman --noconfirm -S snapper snap-pac

echo -e "\033[34m--- Configuration de snapper ---\033[0m"
umount /.snapshots/
rm -rf /.snapshots/
snapper -c root create-config /
snapper -c home create-config /home
chmod a+rx /home/.snapshots
chown :lebotdufutur /home/.snapshots
systemctl enable --now snapper-timeline.timer
systemctl enable --now snapper-cleanup.timer

cat << EOF > /etc/snapper/configs/root
SUBVOLUME="/"
FSTYPE="btrfs"
QGROUP=""
SPACE_LIMIT="0.5"
FREE_LIMIT="0.2"
ALLOW_USERS=""
ALLOW_GROUPS=""
SYNC_ACL="no"
BACKGROUND_COMPARISON="yes"
NUMBER_CLEANUP="yes"
NUMBER_MIN_AGE="1800"
NUMBER_LIMIT="30"
NUMBER_LIMIT_IMPORTANT="10"
TIMELINE_CREATE="yes"
TIMELINE_CLEANUP="yes"
TIMELINE_MIN_AGE="1800"
TIMELINE_LIMIT_HOURLY="5"
TIMELINE_LIMIT_DAILY="5"
TIMELINE_LIMIT_WEEKLY="5"
TIMELINE_LIMIT_MONTHLY="0"
TIMELINE_LIMIT_YEARLY="0"
EMPTY_PRE_POST_CLEANUP="yes"
EMPTY_PRE_POST_MIN_AGE="1800"
EOF

cat << EOF > /etc/snapper/configs/home
SUBVOLUME="/home"
FSTYPE="btrfs"
QGROUP=""
SPACE_LIMIT="0.5"
FREE_LIMIT="0.2"
ALLOW_USERS="lebotdufutur"
ALLOW_GROUPS=""
SYNC_ACL="no"
BACKGROUND_COMPARISON="yes"
NUMBER_CLEANUP="yes"
NUMBER_MIN_AGE="1800"
NUMBER_LIMIT="30"
NUMBER_LIMIT_IMPORTANT="10"
TIMELINE_CREATE="yes"
TIMELINE_CLEANUP="yes"
TIMELINE_MIN_AGE="1800"
TIMELINE_LIMIT_HOURLY="5"
TIMELINE_LIMIT_DAILY="5"
TIMELINE_LIMIT_WEEKLY="5"
TIMELINE_LIMIT_MONTHLY="0"
TIMELINE_LIMIT_YEARLY="0"
EMPTY_PRE_POST_CLEANUP="yes"
EMPTY_PRE_POST_MIN_AGE="1800"
EOF

echo -e "\033[34m--- Création des premiers instantanés ---\033[0m"
snapper -c root create --type single --cleanup-algorithm number --description 'backup_root'
snapper -c home create --type single --cleanup-algorithm number --description 'backup_home'

echo -e "\033[34m--- Configuration de l'adresse ip fixe ---\033[0m"
nmcli connection modify "$(nmcli -t -f NAME connection show --active | head -n 1)" ipv4.method manual \
                                                                                 ipv4.address 192.168.0.25/24 \
                                                                                 ipv4.gateway 192.168.0.1 \
                                                                                 ipv4.dns 192.168.0.1

echo -en "\033[34m--- Création des dossiers pour crowdsec ---\033[0m\n\n"
sudo touch /var/log/auth.log
sudo chown lebotdufutur:lebotdufutur /var/log/auth.log
sudo mkdir /data
sudo chown lebotdufutur:lebotdufutur /data

echo -en "\033[34m--- Mise en place de la sécurité pour root ---\033[0m\n\n"
# Empêcher le shell root de fonctionner
sed -i '1 s/root:x:0:0::\/root:\/usr\/bin\/bash/root:x:0:0::\/root:\/usr\/bin\/nologin/' /etc/passwd
# Désactiver la connexion root via le périphérique de console (TTY)
mv /etc/securetty /etc/securetty.orig
touch /etc/securetty
chmod 600 /etc/securetty
# Désactiver la connexion root en ssh
bash -c 'echo "PermitRootLogin no" >> /etc/ssh/sshd_config'

