#!/bin/bash

if [[ $(whoami) = "root" ]]
then
    echo "Il ne faut pas être root"
    exit 1
fi

echo -en "\033[34m\t----- Post installation -----\033[0m\n\n"

echo -en "\033[34m\t----- Partie administrateur -----\033[0m\n\n"

sudo ./post_install_root

echo -en "\033[34m\t----- Partie utilisateur -----\033[0m\n\n"

echo -e "\033[34m--- Installation de ma configuration ---\033[0m"
cd ~
wget https://github.com/fadri14/dotfiles/archive/refs/heads/main.zip
unzip main.zip

folders="\
fish
nvim
starship.toml"

for folder in $folders
do
    rm -fr ~/.config/${folder}
    mv dotfiles-main/myconfig/${folder} ~/.config
done

rm -fr main.zip dotfiles-main

echo -e "\033[34m--- Installation de yay ---\033[0m"
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si --noconfirm
cd ..
rm -fr yay

echo -e "\033[34m--- Installation des paquets du AUR ---\033[0m"
yay --noconfirm -S arch-update
yay --noconfirm -S ufw-docker

echo -e "\033[34m--- Configuration de ufw pour docker ---\033[0m"
sudo ufw-docker install
sudo systemctl restart ufw

echo -e "\033[34m--- Configuration de crontab pour duckdns ---\033[0m"
(crontab -l; echo "*/5 * * * * /home/lebotdufutur/serveur/duckdns/duck.sh >/dev/null 2>&1") | crontab -

echo -e "\033[34m--- Installation de la configuration de neovim ---\033[0m"
nvim .config/nvim/lua/adrien-config/packer.lua

echo -e "\033[34m--- Fin de la post-installation ---\033[0m"

echo "Il faut lancer la commande 'yay --noconfirm -S docker-rootless-extras' et faire ce qu'il dit"
