#!/bin/bash

if [[ $(whoami) != "root" ]]
then
    echo "Il faut être root"
    exit 1
fi

packages="
niri
foot
fuzzel
waybar
mako
swww
gtklock
helix
evince
nautilus
signal-desktop
gnome-calculator
xournalpp
fzf
eog
glances
ripgrep
gnome-disk-utility
fastfetch
pass
keychain
zenity
discord
wtype
starship
ufw
libreoffice-still
git
gammastep
yt-dlp
keepassxc
pkgstats
zoxide
rustup
fish
chezmoi
eza
nextcloud-client

openssh
gnome-keyring
seahorse
xdg-desktop-portal-gtk
xdg-desktop-portal-gnome
xdg-utils
xwayland-satellite
polkit
smartmontools
wget
wireless_tools
wpa_supplicant
sddm
pacman-contrib
libnotify
libinput
acpi
mplayer
whois
ttf-hack-nerd
pipewire
pipewire-alsa
pipewire-audio
pipewire-pulse
x86_energy_perf_policy
terminus-font
ethtool
bluez
bluez-utils
blueman
adwaita-cursors
adwaita-icon-theme
binutils
cryptsetup
gnupg
libadwaita
pavucontrol
tar
unrar
rebuild-detector
kwayland5

intel-media-driver
libva-intel-driver
libva-mesa-driver
mesa
vulkan-intel
vulkan-nouveau
vulkan-radeon
xf86-video-amdgpu
xf86-video-ati
xf86-video-nouveau
xorg-server
xorg-xinit
"

for package in $packages
do
    if [[ packages != "" ]]
    then
        pacman -S --needed --noconfirm $package &> /dev/null

        if [[ "$?" == "0" ]]
        then
            echo -e "\033[32mOK\033[0m $package"
        else
            echo -e "\033[31mERREUR\033[0m $package"
        fi
    fi
done

