#!/bin/bash

if [[ $(whoami) != "root" ]]
then
    echo "Il faut être root"
    exit 1
fi

packages="
neovim
alacritty
evince
nautilus
gnome-calculator
ranger
xournalpp
fzf
eog
glances
waylock
ripgrep
rofi
waybar
wl-mirror
wl-clipboard
dunst
gnome-disk-utility
mpd
mpc
fastfetch
pass
keychain
texlive
grim
fish
zenity
discord
sddm
wtype
starship
ufw
libreoffice-still
git
gammastep
yt-dlp
id3v2
keepassxc

pacman-contrib
python-pip
python-certifi
texlive-langfrench
python-pygments
libffi
python-cffi
python-pynvim
libnotify
libinput
libreoffice-still
acpi
mplayer
go
swaybg

wayland
xorg-xwayland
irqbalance
cpupower
pipewire
pipewire-alsa
pipewire-audio
pipewire-pulse
x86_energy_perf_policy
rxvt-unicode
terminus-font
whois
ethtool
foomatic-db
foomatic-db-ppds
foomatic-db-gutenprint-ppds
foomatic-db-nonfree
foomatic-db-nonfree-ppds
gutenprint
system-config-printer
transmission-gtk
bluez
bluez-utils
bluez-plugins
ttf-hack-nerd
xdg-utils
intel-media-driver
intel-gmmlib
cups
cups-filters
cups-pdf
avahi
bash
bash-completion
kwayland5

adwaita-cursors
adwaita-icon-theme
binutils
blueman
cryptsetup
dconf
default-cursors
desktop-file-utils
gnu-free-fonts
gnupg
gnutls
gtk-layer-shell
gtk-update-icon-cache
qt5-wayland
hunspell
libadwaita
pavucontrol
tar
vulkan-headers
vulkan-icd-loader
vulkan-intel
xdg-desktop-portal-wlr
xdg-desktop-portal-gtk
xdg-dbus-proxy
xdg-user-dirs
noto-fonts-emoji
fwupd
rebuild-detector
unrar
"

for package in $packages
do
    if [[ packages != "" ]]
    then
        pacman -S --needed --noconfirm $package &> /dev/null

        if [[ "$?" == "0" ]]
        then
            echo -e "\033[32mOK\033[0m $package"
        else
            echo -e "\033[31mERREUR\033[0m $package"
        fi
    fi
done

